# platform :ios, '7.0'
platform :osx, '10.8'

source 'https://github.com/CocoaPods/Specs.git'
link_with 'GDStore', 'UnitTest'

pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc.git'
pod 'GDJson', :git => 'https://github.com/goodow/GDJson.git'
pod 'GDChannel', :git => 'https://github.com/goodow/GDChannel.git'
pod 'GDStore', :path => '..'
# pod 'PonyDebugger', '~> 0.3.0'

