platform :ios, '7.0'

pod 'J2ObjC', :git => 'https://github.com/goodow/j2objc.git', :commit => '32284814b6352a8d8458d1b866c59f830a2dce42'
pod 'GDJson', :git => 'https://github.com/goodow/GDJson.git'
pod 'GDChannel', :git => 'https://github.com/goodow/GDChannel.git'
pod 'GDStore', :path => '..'
# pod 'PonyDebugger', '~> 0.3.0'

link_with ['GDStore', 'Playground']
