//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/com/goodow/realtime/channel/http/objc/ObjCHttpResponse.java
//
//  Created by retechretech on 13-5-21.
//

#import "com/goodow/realtime/channel/http/objc/ObjCHttpResponse.h"

@implementation ComGoodowRealtimeChannelHttpObjcObjCHttpResponse

- (NSString *)getContent {
  return nil;
}

- (NSString *)getContentEncoding {
  return nil;
}

- (long long int)getContentLength {
  return 0;
}

- (NSString *)getContentType {
  return nil;
}

- (int)getHeaderCount {
  return 0;
}

- (NSString *)getHeaderNameWithInt:(int)index {
  return nil;
}

- (NSString *)getHeaderValueWithInt:(int)index {
  return nil;
}

- (NSString *)getReasonPhrase {
  return nil;
}

- (int)getStatusCode {
  return 0;
}

- (NSString *)getStatusLine {
  return nil;
}

- (id)init {
  return [super init];
}

@end
